/**
 * Incoterms® 2020 — 11 条规则的结构化数据
 * 数据来源：ICC 官方出版物
 *   - inco2020_eng_intro.pdf (官方导言)
 *   - incoterms_2020_checklist_2024-update.pdf (决策清单)
 *   - incoterms_2020_wallchart-a4.pdf (挂图)
 *
 * 每条规则包含：
 *   code, name, nameCN      — 缩写 / 英文全称 / 中文全称
 *   group                    — "any" (任何运输方式) / "sea" (海运及内河水运)
 *   oldGroup                 — E / F / C / D 传统分组
 *   summary, summaryCN       — 一句话定位
 *   riskPoint, riskPointCN   — 风险转移点
 *   sellerCarriage           — 卖方是否安排主运输
 *   buyerCarriage            — 买方是否安排主运输
 *   sellerInsurance          — 卖方是否承担保险
 *   exportClearance          — "seller" / "buyer"
 *   importClearance          — "seller" / "buyer"
 *   sellerCosts, buyerCosts  — 费用清单
 *   articles                 — 十大义务 A/B 摘要
 *   caution, cautionCN       — 注意事项
 */

const incotermsData = [
  // ==================== 任何运输方式 (7条) ====================
  {
    code: "EXW",
    name: "Ex Works",
    nameCN: "工厂交货",
    name_es: "En Fábrica",
    name_fr: "À l'usine",
    name_de: "Ab Werk",
    name_ja: "工場渡し",
    group: "any",
    oldGroup: "E",
    loading: "buyer",
    unloading: "buyer",
    summary: "Seller makes goods available at own premises; buyer bears all costs and risks from there.",
    summaryCN: "卖方在自有场所（工厂/仓库）将货物备妥，买方承担此后一切费用与风险。",
    riskPoint: "Seller's premises — when goods are placed at buyer's disposal, NOT loaded.",
    riskPointCN: "卖方场所 — 货物交由买方处置时（不负责装货）。",
    sellerCarriage: false,
    buyerCarriage: true,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "buyer",
    importClearance: "buyer",
    sellerCosts: ["将货物备妥于约定地点"],
    buyerCosts: ["装货", "出口清关", "主运输", "保险", "进口清关", "卸货", "运至最终目的地"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在约定时间和地点将货物交由买方处置（不装货）",
      B2: "在卖方交付后收取货物",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "无义务安排运输",
      B4: "安排并支付全部运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供交货凭证",
      B6: "接受交货凭证",
      A7: "无出口/进口清关义务",
      B7: "办理出口及进口清关",
      A8: "必要的货物检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用",
      B9: "承担 A2 之后的一切费用",
      A10: "通知买方货物已备妥",
      B10: "通知卖方接收货物的时间"
    },
    caution: "EXW is primarily for domestic trade. In international sales, the seller cannot obtain export documentation and the buyer may face loading difficulties. Consider FCA instead.",
    cautionCN: "EXW 主要用于国内贸易。国际贸易中卖方无法获得出口单证，买方可能面临装货困难。建议考虑 FCA。",
    suitableFor: "Domestic transactions only; avoid for international trade.",
    suitableForCN: "仅适合国内交易；国际贸易中应避免使用。"
  },
  {
    code: "FCA",
    name: "Free Carrier",
    nameCN: "货交承运人",
    name_es: "Franco Porteador",
    name_fr: "Franco transporteur",
    name_de: "Frei Frachtführer",
    name_ja: "運送人渡し",
    group: "any",
    oldGroup: "F",
    loading: "seller",
    unloading: "buyer",
    summary: "Seller delivers goods to carrier nominated by buyer at named place; export cleared by seller.",
    summaryCN: "卖方将货物在指定地点交付给买方指定的承运人，卖方负责出口清关。",
    riskPoint: "When goods are handed over to the buyer's carrier at the named place.",
    riskPointCN: "货物在指定地点交付给买方承运人时。",
    sellerCarriage: false,
    buyerCarriage: true,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "将货物交给买方承运人（卖方场所则含装货）"],
    buyerCosts: ["主运输", "保险", "进口清关", "目的地卸货"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在指定地点将货物交付给买方指定的承运人",
      B2: "接收卖方已交付的货物",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "无义务安排运输（可协助）",
      B4: "安排并支付主运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供交货凭证；买方可以指示承运人签发已装船提单（2020新增）",
      B6: "接受交货凭证",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用（含出口清关费）",
      B9: "承担 A2 之后的一切费用",
      A10: "通知买方货物已交付承运人",
      B10: "通知卖方承运人信息及接收时间"
    },
    caution: "FCA 2020 introduces an option for buyer to instruct carrier to issue on-board bill of lading to seller — useful for letter of credit transactions.",
    cautionCN: "FCA 2020 新增选项：买方可指示承运人向卖方签发已装船提单，便于信用证结算。",
    suitableFor: "Containerized cargo, multimodal transport, delivery at inland terminals. Better than FOB for containers.",
    suitableForCN: "集装箱货物、多式联运、在内陆或港口终端交货。对集装箱货运优于 FOB。"
  },
  {
    code: "CPT",
    name: "Carriage Paid To",
    nameCN: "运费付至",
    name_es: "Transporte Pagado Hasta",
    name_fr: "Port payé jusqu'à",
    name_de: "Frachtfrei",
    name_ja: "輸送費込み",
    group: "any",
    oldGroup: "C",
    loading: "seller",
    unloading: "buyer",
    summary: "Seller pays carriage to named destination; risk transfers when goods handed to first carrier.",
    summaryCN: "卖方支付运费至指定目的地，但风险在货物交给第一承运人时转移给买方。",
    riskPoint: "When goods are handed over to the first carrier at the place of shipment.",
    riskPointCN: "货物在装运地交给第一承运人时。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "主运输运费至指定目的地"],
    buyerCosts: ["保险", "进口清关", "目的地卸货及后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "将货物在约定时间和地点交给承运人",
      B2: "在 A2 后接收货物",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排并支付至指定目的地的运输",
      B4: "无义务安排运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供运输单据",
      B6: "接受运输单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用 + 运费至目的地",
      B9: "承担 A2 之后的费用（运费除外）",
      A10: "通知买方货物已交付承运人",
      B10: "通知卖方接收货物的时间和地点"
    },
    caution: "Risk and cost split at different points: seller pays for carriage to destination, but risk transfers to buyer much earlier (at shipment).",
    cautionCN: "风险与费用分离：卖方承担到目的地的运费，但风险在装运时就已转移给买方。",
    suitableFor: "Multimodal transport where seller wants to control and pay for carriage, but not bear transit risk.",
    suitableForCN: "多式联运，卖方希望控制和支付运输但不承担运输风险时。"
  },
  {
    code: "CIP",
    name: "Carriage and Insurance Paid To",
    nameCN: "运费和保险费付至",
    name_es: "Transporte y Seguro Pagados Hasta",
    name_fr: "Port payé, assurance comprise jusqu'à",
    name_de: "Frachtfrei versichert",
    name_ja: "輸送費保険料込み",
    group: "any",
    oldGroup: "C",
    loading: "seller",
    unloading: "buyer",
    summary: "Like CPT plus seller must obtain all-risk insurance cover (Institute Cargo Clauses A).",
    summaryCN: "与 CPT 类似，但卖方必须办理全险（协会货物条款 A）。",
    riskPoint: "When goods are handed over to the first carrier at the place of shipment.",
    riskPointCN: "货物在装运地交给第一承运人时。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: true,
    insuranceNote: "协会货物条款 A（全险）",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "主运输运费至指定目的地", "保险费（全险）"],
    buyerCosts: ["进口清关", "目的地卸货及后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "将货物在约定时间和地点交给承运人",
      B2: "在 A2 后接收货物",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排并支付至指定目的地的运输",
      B4: "无义务安排运输",
      A5: "办理保险（协会货物条款A/全险），保险金额至少为合同价的110%",
      B5: "自行决定是否追加保险",
      A6: "提供运输单据及保险单据",
      B6: "接受运输单据及保险单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用 + 运费 + 保险费",
      B9: "承担 A2 之后的费用（运费和保险费除外）",
      A10: "通知买方货物已交付承运人",
      B10: "通知卖方接收货物的时间和地点"
    },
    caution: "2020 key change: CIP insurance upgraded from Clause (C) minimum cover to Clause (A) all-risk cover. This is significantly higher protection than CIF.",
    cautionCN: "2020 重大变化：CIP 的保险从最低险（C条款）升级为全险（A条款），比 CIF 的保险保障更高。",
    suitableFor: "Multimodal transport, especially manufactured goods where buyer wants comprehensive insurance covered by seller.",
    suitableForCN: "多式联运，尤其适合制成品贸易，买方希望卖方办理全面保险时。"
  },
  {
    code: "DAP",
    name: "Delivered at Place",
    nameCN: "目的地交货",
    name_es: "Entregada en Lugar",
    name_fr: "Rendu au lieu de destination",
    name_de: "Geliefert benannter Ort",
    name_ja: "仕向地持込渡し",
    group: "any",
    oldGroup: "D",
    loading: "seller",
    unloading: "buyer",
    summary: "Seller delivers when goods are placed at buyer's disposal at named destination, ready for unloading (buyer unloads).",
    summaryCN: "卖方将货物运至指定目的地，交由买方处置（买方负责卸货）。",
    riskPoint: "At the named destination when goods are placed at buyer's disposal on the arriving transport.",
    riskPointCN: "货物运抵指定目的地，交由买方处置时。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: false,
    insuranceNote: "无义务（但建议卖方投保）",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "全部运输至指定目的地", "（建议）运输保险"],
    buyerCosts: ["卸货", "进口清关", "运至最终地点"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "将货物运至指定目的地并交由买方处置（不卸货）",
      B2: "在货物运抵后接收货物并卸货",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排或自行组织全部运输至目的地",
      B4: "无义务安排运输",
      A5: "无义务办理保险（但承担运输风险前建议办理）",
      B5: "自行决定是否投保",
      A6: "提供买方提货所需的单据",
      B6: "接受提货单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的全部费用",
      B9: "承担 A2 之后的费用",
      A10: "通知买方货物发运信息",
      B10: "通知卖方接收货物的时间和地点"
    },
    caution: "Seller does NOT unload goods at destination. If seller needs to unload, use DPU instead. Seller does NOT handle import clearance — use DDP for that.",
    cautionCN: "卖方在目的地不负责卸货。如卖方需要卸货，请使用 DPU。卖方不负责进口清关——如需请用 DDP。",
    suitableFor: "When seller can arrange transport to buyer's country but cannot or does not want to handle import clearance.",
    suitableForCN: "卖方能安排运输到买方国家，但不能或不想办理进口清关时。"
  },
  {
    code: "DPU",
    name: "Delivered at Place Unloaded",
    nameCN: "目的地卸货后交货",
    name_es: "Entregada en Lugar Descargada",
    name_fr: "Rendu au lieu de destination déchargé",
    name_de: "Geliefert benannter Ort entladen",
    name_ja: "荷卸込持込渡し",
    group: "any",
    oldGroup: "D",
    loading: "seller",
    unloading: "seller",
    summary: "Like DAP but seller also unloads goods from arriving transport at named destination.",
    summaryCN: "与 DAP 类似，但卖方还要负责在指定目的地将货物从运输工具上卸下。",
    riskPoint: "At the named destination after goods have been unloaded from the arriving transport.",
    riskPointCN: "货物运抵指定目的地并从运输工具上卸下后。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: false,
    insuranceNote: "无义务（但建议卖方投保）",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "全部运输至指定目的地", "目的地卸货", "（建议）运输保险"],
    buyerCosts: ["进口清关", "运至最终地点"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "将货物运至指定目的地并卸货后交由买方处置",
      B2: "在货物卸货后接收货物",
      A3: "风险在 A2 完成时（卸货后）转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排或自行组织全部运输至目的地并卸货",
      B4: "无义务安排运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供买方提货所需的单据",
      B6: "接受提货单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的全部费用（含卸货费）",
      B9: "承担 A2 之后的费用",
      A10: "通知买方货物发运信息",
      B10: "通知卖方接收货物的时间和地点"
    },
    caution: "Formerly DAT (Delivered at Terminal) in Incoterms 2010. Renamed to DPU to emphasize delivery can be at any place, not just a terminal. Seller MUST ensure the named place allows unloading.",
    cautionCN: "Incoterms 2010 中名为 DAT。现更名为 DPU，强调目的地可以是任意地点而非仅限运输终端。卖方必须确保指定地点允许卸货。",
    suitableFor: "When seller can arrange transport to buyer's destination AND can unload there.",
    suitableForCN: "卖方能安排运输到买方目的地且能在该地卸货时。"
  },
  {
    code: "DDP",
    name: "Delivered Duty Paid",
    nameCN: "完税后交货",
    name_es: "Entregada Derechos Pagados",
    name_fr: "Rendu droits acquittés",
    name_de: "Geliefert verzollt",
    name_ja: "関税込持込渡し",
    group: "any",
    oldGroup: "D",
    loading: "seller",
    unloading: "seller",
    summary: "Maximum obligation for seller: delivers goods cleared for import at named destination, all duties paid.",
    summaryCN: "卖方责任最大：将货物运至指定目的地，完成进口清关并缴纳关税后交付买方。",
    riskPoint: "At the named destination after import clearance and duties paid.",
    riskPointCN: "货物运抵指定目的地，完成进口清关并缴税后。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: false,
    insuranceNote: "无义务（但强烈建议卖方投保）",
    exportClearance: "seller",
    importClearance: "seller",
    sellerCosts: ["出口清关", "全部运输", "（建议）运输保险", "进口清关", "进口关税/增值税"],
    buyerCosts: ["卸货（除非约定由卖方负责）"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "将货物运至指定目的地，完成进口清关后交由买方处置",
      B2: "在货物交付后接收货物",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排或自行组织全部运输至目的地",
      B4: "无义务安排运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供买方提货所需的单据",
      B6: "接受提货单据",
      A7: "办理出口及进口清关",
      B7: "在卖方需要时协助进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的一切费用（含关税）",
      B9: "承担 A2 之后的费用",
      A10: "通知买方货物发运信息",
      B10: "通知卖方接收货物的时间和地点"
    },
    caution: "Seller handles import clearance in buyer's country — may be legally or physically impossible. Seller may not be able to recover import VAT. Consider DAP or DPU instead.",
    cautionCN: "卖方需在买方国家办理进口清关——这在法律上或操作上可能行不通。卖方可能无法退回进口增值税。建议考虑 DAP 或 DPU。",
    suitableFor: "Only when seller is fully familiar with and capable of handling import formalities in buyer's country.",
    suitableForCN: "仅当卖方完全熟悉且能办理买方国家进口手续时使用。"
  },

  // ==================== 海运及内河水运 (4条) ====================
  {
    code: "FAS",
    name: "Free Alongside Ship",
    nameCN: "船边交货",
    name_es: "Franco al Costado del Buque",
    name_fr: "Franco le long du navire",
    name_de: "Frei Längsseite Schiff",
    name_ja: "船側渡し",
    group: "sea",
    oldGroup: "F",
    loading: "buyer",
    unloading: "buyer",
    summary: "Seller delivers goods alongside the vessel at the named port of loading; export cleared by seller.",
    summaryCN: "卖方将货物在指定装运港的船边交付，卖方负责出口清关。",
    riskPoint: "When goods are placed alongside the vessel at the named port of loading.",
    riskPointCN: "货物在指定装运港的船边放置时。",
    sellerCarriage: false,
    buyerCarriage: true,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "将货物运至装运港船边"],
    buyerCosts: ["装船", "主运输", "保险", "进口清关", "卸货", "后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在指定装运港将货物放置船边",
      B2: "自船边接收货物并装船",
      A3: "风险在 A2 完成时转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "无义务安排运输",
      B4: "安排并支付海运及后续运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供交货凭证",
      B6: "接受交货凭证",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用（含出口清关费）",
      B9: "承担 A2 之后的一切费用",
      A10: "通知买方货物已放置船边",
      B10: "通知卖方船舶信息"
    },
    caution: "FAS is only for sea and inland waterway transport. Not suitable for containerized cargo — use FCA instead.",
    cautionCN: "FAS 仅适用于海运及内河水运。不适合集装箱货物——应用 FCA 替代。",
    suitableFor: "Bulk cargo or heavy-lift where goods are placed alongside ship rather than loaded by seller.",
    suitableForCN: "散货或重件货，货物在船边交付而非由卖方装船时。"
  },
  {
    code: "FOB",
    name: "Free On Board",
    nameCN: "船上交货",
    name_es: "Franco a Bordo",
    name_fr: "Franco à bord",
    name_de: "Frei an Bord",
    name_ja: "本船渡し",
    group: "sea",
    oldGroup: "F",
    loading: "seller",
    unloading: "buyer",
    summary: "Seller delivers goods on board the vessel at named port of loading; export cleared by seller.",
    summaryCN: "卖方将货物在指定装运港装上买方指定的船舶，卖方负责出口清关。",
    riskPoint: "When goods are placed on board the vessel at the named port of loading.",
    riskPointCN: "货物在指定装运港装上船时。",
    sellerCarriage: false,
    buyerCarriage: true,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "将货物运至装运港并装船"],
    buyerCosts: ["主运输（海运）", "保险", "进口清关", "卸货", "后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在指定装运港将货物装上买方指定的船舶",
      B2: "接收已装船货物",
      A3: "风险在 A2 完成时（装船后）转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "无义务安排运输",
      B4: "安排并支付海运及后续运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供交货凭证",
      B6: "接受交货凭证",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的所有费用（含装船费）",
      B9: "承担 A2 之后的一切费用",
      A10: "通知买方货物已装船",
      B10: "通知卖方船舶信息及装船时间"
    },
    caution: "FOB should NOT be used for containerized cargo. The container is typically handed to carrier at a terminal before loading — use FCA instead. 'FOB inland point' is a common mistake.",
    cautionCN: "FOB 不应该用于集装箱货物。集装箱通常在装船前就在堆场交给承运人——应用 FCA 替代。\"FOB 内陆点\"是常见错误用法。",
    suitableFor: "Traditional bulk cargo or general cargo loaded directly on board vessel. NOT for containers.",
    suitableForCN: "传统散货或件杂货直接装船。不适合集装箱。"
  },
  {
    code: "CFR",
    name: "Cost and Freight",
    nameCN: "成本加运费",
    name_es: "Costo y Flete",
    name_fr: "Coût et fret",
    name_de: "Kosten und Fracht",
    name_ja: "運賃込み",
    group: "sea",
    oldGroup: "C",
    loading: "seller",
    unloading: "buyer",
    summary: "Seller pays freight to named port of destination; risk transfers when goods are on board at port of loading.",
    summaryCN: "卖方支付运费至指定目的港，但风险在装运港货物装上船时转移给买方。",
    riskPoint: "When goods are placed on board the vessel at the port of loading.",
    riskPointCN: "货物在装运港装上船时。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: false,
    insuranceNote: "无义务",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "装船", "海运运费至指定目的港"],
    buyerCosts: ["保险", "目的地港卸货", "进口清关", "后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在装运港将货物装上船",
      B2: "接收货物",
      A3: "风险在 A2 完成时（装船后）转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排并支付至指定目的港的海运",
      B4: "无义务安排运输",
      A5: "无义务办理保险",
      B5: "自行决定是否投保",
      A6: "提供运输单据",
      B6: "接受运输单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用 + 海运运费至目的港",
      B9: "承担 A2 之后的费用（运费除外）",
      A10: "通知买方货物已装船",
      B10: "通知卖方接收货物的时间"
    },
    caution: "Risk and cost split at different points — a classic 'shipment contract'. Seller pays freight but risk passes at loading port. Buyer should arrange insurance separately.",
    cautionCN: "风险与费用分离 — 典型的\"装运合同\"。卖方支付运费但风险在装运港已转移。买方应另行办理保险。",
    suitableFor: "Bulk commodity sea transport where buyer arranges own insurance.",
    suitableForCN: "散货海运，买方自行办理保险时。"
  },
  {
    code: "CIF",
    name: "Cost Insurance and Freight",
    nameCN: "成本、保险费加运费",
    name_es: "Costo, Seguro y Flete",
    name_fr: "Coût, assurance et fret",
    name_de: "Kosten, Versicherung und Fracht",
    name_ja: "運賃保険料込み",
    group: "sea",
    oldGroup: "C",
    loading: "seller",
    unloading: "buyer",
    summary: "Like CFR plus seller must obtain minimum insurance cover (Institute Cargo Clauses C).",
    summaryCN: "与 CFR 类似，但卖方还必须办理最低险别的海运保险（协会货物条款 C）。",
    riskPoint: "When goods are placed on board the vessel at the port of loading.",
    riskPointCN: "货物在装运港装上船时。",
    sellerCarriage: true,
    buyerCarriage: false,
    sellerInsurance: true,
    insuranceNote: "协会货物条款 C（最低险）",
    exportClearance: "seller",
    importClearance: "buyer",
    sellerCosts: ["出口清关", "装船", "海运运费至指定目的港", "保险费（最低险）"],
    buyerCosts: ["目的地港卸货", "进口清关", "后续运输"],
    articles: {
      A1: "提供符合合同的货物及商业发票",
      B1: "支付合同价款",
      A2: "在装运港将货物装上船",
      B2: "接收货物",
      A3: "风险在 A2 完成时（装船后）转移给买方",
      B3: "自 A2 完成时承担货物风险",
      A4: "安排并支付至指定目的港的海运",
      B4: "无义务安排运输",
      A5: "办理保险（协会货物条款C/最低险），保险金额至少为合同价的110%",
      B5: "自行决定是否追加保险",
      A6: "提供运输单据及保险单据",
      B6: "接受运输单据及保险单据",
      A7: "办理出口清关",
      B7: "办理进口清关",
      A8: "必要的检查与包装",
      B8: "无特别义务",
      A9: "承担 A2 之前的费用 + 运费 + 保险费",
      B9: "承担 A2 之后的费用（运费和保险费除外）",
      A10: "通知买方货物已装船",
      B10: "通知卖方接收货物的时间"
    },
    caution: "CIF insurance is MINIMUM cover (Clause C) only — unlike CIP which requires all-risk (Clause A). CIF is retained mainly for commodity trades. For manufactured goods, consider CIP.",
    cautionCN: "CIF 的保险仅为最低险（C条款），与 CIP 要求的全险（A条款）不同。CIF 主要保留用于大宗商品贸易。制成品建议考虑 CIP。",
    suitableFor: "Bulk commodity sea transport; traditional maritime trade where minimum insurance is acceptable.",
    suitableForCN: "散货海运大宗商品贸易；传统海运交易，最低保险可接受时。"
  }
];

// 按分组索引
const anyModeRules = incotermsData.filter(r => r.group === "any");
const seaModeRules = incotermsData.filter(r => r.group === "sea");
